### ISSUE TITLE
Change setup.py to open README.md file from root directory.

### ISSUE THREAD

**Issue by abhinavsp0730** [abhinavsp0730/khronos#5]
Right now there's a bug in `setup.py` file. 
https://github.com/abhinavsp0730/khronos/blob/a9f09e6a81c89808452917325ded0aff78bb39ab/Khronos/setup.py#L7

So, whenever I have to push a new version to PyPi, I have to manually put `README.md` file to dir in which `setup.py` file is. 

So, make the changes in 
https://github.com/abhinavsp0730/khronos/blob/a9f09e6a81c89808452917325ded0aff78bb39ab/Khronos/setup.py#L7
in way it'll open the  `README.md` file from root dir.

**Comment by Paul-Annay** [comment]
Hey there, can I work on this?

**Comment by abhinavsp0730** [comment]
Assigned the issue to you. All the Best :).
